# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'debrief.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtMultimedia import QSoundEffect
from PyQt5.QtCore import QUrl

class Ui_Debrief(object):

    def __init__(self):
        self.marble = 0

    def setupUi(self, Form):

        Form.setObjectName("Form")
        Form.setFixedSize(640, 480)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(160, 60, 351, 91))
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(120, 300, 151, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(360, 300, 161, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Experiment"))
        Form.setStyleSheet("background-color: #4E75CF")
        self.label.setText(_translate("Form", "Conguratulations you won!"))
        self.pushButton.setText(_translate("Form", "Next participant"))
        self.pushButton.setStyleSheet("background-color: #6997D3")
        self.pushButton_2.setText(_translate("Form", "Finish"))
        self.pushButton_2.setStyleSheet("background-color: #6997D3")

