# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setFixedSize(640, 480)
        # initiate input validator to be only Integer
        self.onlyInt = QtGui.QIntValidator(18, 99)
        self.lineEdit = QtWidgets.QLineEdit(Form)
        # set max length 0f input
        self.lineEdit.setMaxLength(2)
        self.lineEdit.setValidator(self.onlyInt)
        self.lineEdit.setGeometry(QtCore.QRect(150, 60, 113, 22))
        self.lineEdit.setObjectName("lineEdit")
        self.comboBox = QtWidgets.QComboBox(Form)
        self.comboBox.setGeometry(QtCore.QRect(150, 180, 91, 21))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(40, 60, 91, 20))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(40, 120, 55, 20))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(40, 180, 101, 20))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(40, 82, 140, 20))
        self.label_4.setFont(QtGui.QFont("Arial font", 6))
        self.label_4.setObjectName("label_4")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(40, 280, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.comboBox_2 = QtWidgets.QComboBox(Form)
        self.comboBox_2.setGeometry(QtCore.QRect(150, 120, 91, 21))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Experiment"))
        Form.setStyleSheet("background-color: #4E75CF")
        self.lineEdit.setStyleSheet("background-color: #8C9FC9")
        self.lineEdit.setStyleSheet("border: 1px solid black;")
        self.comboBox.setItemText(0, _translate("Form", "1_level"))
        self.comboBox.setItemText(1, _translate("Form", "2_level"))
        self.comboBox.setItemText(2, _translate("Form", "3_level"))
        self.comboBox.setItemText(3, _translate("Form", "4_level"))
        self.comboBox.setItemText(4, _translate("Form", "5_level"))
        self.comboBox.setItemText(5, _translate("Form", "6_level"))
        self.comboBox.setItemText(6, _translate("Form", "7_level"))
        self.comboBox.setItemText(7, _translate("Form", "8_level"))
        self.comboBox.setStyleSheet("background-color: #6997D3")
        self.label.setText(_translate("Form", "  Age:"))
        self.label.setStyleSheet("background-color: #8C9FC9")
        self.label_2.setText(_translate("Form", "  Gender"))
        self.label_2.setStyleSheet("background-color: #8C9FC9")
        self.label_3.setText(_translate("Form", "  Education level"))
        self.label_3.setStyleSheet("background-color: #8C9FC9")
        self.label_4.setText(_translate("Form", "(you must be over 17)"))
        self.pushButton.setText(_translate("Form", "Confirm"))
        self.pushButton.setStyleSheet("background-color: #6997D3")
        self.comboBox_2.setItemText(0, _translate("Form", "Male"))
        self.comboBox_2.setItemText(1, _translate("Form", "Female"))
        self.comboBox_2.setItemText(2, _translate("Form", "Other"))
        self.comboBox_2.setStyleSheet("background-color: #6997D3")

